# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      # Fixes IPv6 vs IPv4 connection issues with Neon/Node 17+
      NODE_OPTIONS: --dns-result-order=ipv4first
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

    steps:
    - uses: actions/checkout@v4

        # 1. Install pnpm first
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10 # Or your specific version

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

        # 3. Install dependencies
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    # - run: pnpm run build --if-present
    - run: pnpm test
    - run: pnpm vitest
    - name: Install Playwright Browsers
      run: pnpm playwright install --with-deps

    # - name: Wake up Neon Database
    #   run: psql "$DATABASE_URL" -c "SELECT 1;"
      # env:
      #   DATABASE_URL: ${{ DATABASE_URL }}

    # - name: Run Playwright Test. Wait on webserver. 
    #   run: pnpm exec wait-on http://localhost:3000 && pnpm playwright test
      # env:
      #   # This maps your GitHub Secret to an environment variable
      #   DATABASE_URL: ${{ DATABASE_URL }}
      #   NODE_ENV: test

    - name: Start Server and Run Tests
      run: |
       pnpm playwright test || (cat server.log && exit 1)
      env:
       POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
